### ISSUE TITLE
iCalender recurrence rule evaluation for time periods

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga-notifications#3]
Repeating events in time periods shall be handled with [recurrence rule (RRULE) from iCalendar (RFC 5545)](https://www.rfc-editor.org/rfc/rfc5545#section-3.3.10). By using a standardized format, we should be able to use a library for evaluation as well as in the future, it should allow for easily implementing imports from existing calendar sources.

## Tasks

- [x] Research available options (i.e. libraries) for RRULE evaluation in Go, give a recommendation on which one to use: https://github.com/Icinga/noma/issues/3#issuecomment-1456374595
- [x] Extend the currently hardcoded test data in [internal/timeperiod/dummy.go](https://github.com/Icinga/noma/blob/main/internal/timeperiod/dummy.go) with corresponding RRULEs.
- [x] Replace the current primitive repetition mechanism in [internal/timeperiod/timeperiod.go](https://github.com/Icinga/noma/blob/main/internal/timeperiod/timeperiod.go) with RRULE evaluation.
- [ ] Write test cases for the implementation. These should also test events that repeat over DST changes (which is something that isn't handled by the current trivial implementation).
