### ISSUE TITLE
Escalation Condition Parsing

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga-notifications#34]
### Tasks

- [ ] Figure out whether started specifying available variables in more detail (especially exact names), if not, make a suggestion.
- [x] Implement parsing and evaluation of escalation conditions, make use of the object filter parser, i.e. #22 should be done first.
- [ ] Integrate it into the config loading (escalations with conditions are skipped at the moment due to missing parsing).
