### ISSUE TITLE
Prepare repo for publication

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga-notifications#72]
### Tasks

- [x] Check if there are any outdated names in the code, if so, update them in a PR (don't forget to rename the `cmd/noma-daemon` directory). https://github.com/Icinga/noma/pull/75
- [x] Add `README.md`: should provide a short summary but mainly instructions on how to get this running (`go build`, make a config file, copy `icinga2.conf` and so on for now). https://github.com/Icinga/noma/pull/74
- [x] Add `LICENSE` (GPLv2 for now, as discussed with @lippserd). https://github.com/Icinga/noma/pull/73
- [x] [Not yet, task for @julianbrost] Rename this repo to `icinga-notifications`.
